package minijava.translate;

import minijava.util.DefaultIndentable;

/**
 * An instance of this class represent a Code fragment generated by
 * the Translate phase that is eventually to be converted into assembly
 * code.
 */
public abstract class Fragment extends DefaultIndentable {

}
