#
# A sample .s file that uses the minjava runtime.
#
# This example was cobbled together by compiling a program with gcc -S
# and then pasting in some of the code generated by my partially implemented
# X86 code generator, doing some manual "register allocation".
#

	.text
.globl mj_main
	.type	mj_main, @function
mj_main:
	pushl	%ebp
	movl	%esp, %ebp
	
L_1:
      movl   $10, %eax
      pushl   %eax
      call    mj_println
      addl    $4, %esp
DONE_2:

	leave
	ret
	.size	mj_main, .-mj_main
	.ident	"GCC: (GNU) 4.2.4 (Ubuntu 4.2.4-1ubuntu3)"
	.section	.note.GNU-stack,"",@progbits
